#!/usr/bin/env python
import abc
import os
import shutil
import json
import fnmatch
import click
import requests
import uuid

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
DEFAULT_REPOS = os.path.join(ROOT_DIR, 'contribs', 'repos')


class SpecScanner(object):

    def __init__(self, root):
        self.root = root

    def scan(self):
        for path, dirs, files in os.walk(self.root, followlinks=True):
            json_files = fnmatch.filter(files, '*.json')
            for filepath, spec in self.filter_specs(path, json_files):
                yield filepath, spec

    def filter_specs(self, path, json_files):
        for filename in json_files:
            filepath = os.path.join(path, filename)
            spec = self.load_spec(filepath)
            if spec and self.is_swagger_spec(spec):
                yield filepath, spec

    def load_spec(self, filepath):
        with open(filepath) as f:
            try:
                return json.loads(f.read())
            except ValueError:
                return None

    def is_swagger_spec(self, spec):
        if 'swagger' not in spec:
            return False
        return str(spec['swagger']) >= "2"


class CatalogBuilder(object):

    __metaclass__ = abc.ABCMeta

    index_filename = "index.json"

    def __init__(self, destination):
        self.destination = destination

    @abc.abstractmethod
    def build(self, scanner):
        pass

    def write_index(self, items):
        items = self.sort_items(items)
        catalog = {'apis': items}
        index_path = os.path.join(self.destination, self.index_filename)
        data = json.dumps(catalog, indent=4, separators=(',', ': '))
        with open(index_path, 'w') as f:
            f.write(data)

    def sort_items(self, items):
        return sorted(items, key=lambda i: i['title'].lower())


class ServerBuilder(CatalogBuilder):

    def build(self, scanner):
        items = self.build_items(scanner)
        self.write_index(items)

    def build_items(self, scanner):
        return [self.build_item(spec) for _, spec in scanner.scan()]

    def build_item(self, spec):
        return {'title': spec['info']['title'],
                'port': spec['x-xivo-port'],
                'path': '{}/doc/api.json'.format(spec['basePath'])}


class StaticBuilder(CatalogBuilder):

    def __init__(self, destination, prefix="/doc/catalog"):
        super(StaticBuilder, self).__init__(destination)
        self.prefix = prefix

    def build(self, scanner):
        items = []
        for filepath, spec in scanner.scan():
            items.append(self.build_item(spec))
            self.copy_spec(spec, filepath)

        self.write_index(items)

    def build_item(self, spec):
        url = "{}/{}.json".format(self.prefix, spec['x-xivo-name'])
        return {'title': spec['info']['title'],
                'url': url}

    def copy_spec(self, spec, filepath):
        filename = "{}.json".format(spec['x-xivo-name'])
        destination = os.path.join(self.destination, filename)
        shutil.copy(filepath, destination)


@click.command()
@click.argument('specs', type=click.Path(exists=True, file_okay=False))
@click.option('--destination', default='catalog', type=click.Path(file_okay=False))
def build_server(specs, destination):
    if not os.path.exists(destination):
        os.makedirs(destination)
    scanner = SpecScanner(specs)
    builder = ServerBuilder(destination)
    builder.build(scanner)


@click.command()
@click.argument('specs', type=click.Path(exists=True, file_okay=False))
@click.option('--destination', default='catalog', type=click.Path(file_okay=False))
@click.option('--prefix', default="/catalog")
def build_static(specs, destination, prefix):
    if not os.path.exists(destination):
        os.makedirs(destination)
    scanner = SpecScanner(specs)
    builder = StaticBuilder(destination, prefix=prefix)
    builder.build(scanner)


@click.command()
@click.option('--repos', type=click.Path(exists=True), default=DEFAULT_REPOS)
@click.option('--branch', default='master')
@click.option('--destination', default='catalog', type=click.Path())
def download(repos, branch, destination):
    if not os.path.exists(destination):
        os.makedirs(destination)

    with open(repos) as f:
        urls = [l.strip().format(branch=branch) for l in f]

    for url in urls:
        download_spec(url, destination)


def download_spec(url, destination):
    filepath = os.path.join(destination, str(uuid.uuid4()) + ".json")

    print "downloading {}".format(url)
    response = requests.get(url, stream=True)
    if response.status_code == 200:
        with open(filepath, 'wb') as f:
            for chunk in response.iter_content(1024):
                f.write(chunk)
    else:
        raise Exception("could not download {}: error {}".format(url, response.status_code))


if __name__ == "__main__":
    group = click.Group()
    group.add_command(build_server)
    group.add_command(build_static)
    group.add_command(download)
    group()
